# Generated by Django 5.1.3 on 2024-11-24 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("cpu", models.PositiveIntegerField()),
                ("ram", models.PositiveIntegerField()),
                ("gpu", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("priority", models.IntegerField()),
                ("cpu_required", models.PositiveIntegerField()),
                ("ram_required", models.PositiveIntegerField()),
                ("gpu_required", models.PositiveIntegerField()),
                ("image_path", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "In Queue"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Deployment Completed"),
                        ],
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="core.cluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin Role"),
                            ("VIEWER", "Viewer Role"),
                            ("DEVELOPER", "Developer Role"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_codes",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cluster",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.organization"
            ),
        ),
        migrations.CreateModel(
            name="ResourceAllocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cpu_allocated", models.PositiveIntegerField()),
                ("ram_allocated", models.PositiveIntegerField()),
                ("gpu_allocated", models.PositiveIntegerField()),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_allocations",
                        to="core.cluster",
                    ),
                ),
                (
                    "deployment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_allocation",
                        to="core.deployment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(
                fields=["status", "priority", "queued_at"],
                name="core_deploy_status_6a280e_idx",
            ),
        ),
    ]
