# Generated by Django 5.1.3 on 2024-11-24 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deployment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invitecode",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membership",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resourceallocation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("FAILED", "Failed"),
                    ("QUEUED", "In Queue"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Deployment Completed"),
                ],
                default="QUEUED",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="cluster",
            index=models.Index(
                fields=["created_at", "is_deleted"],
                name="core_cluste_created_99b443_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(
                fields=["created_at", "is_deleted"],
                name="core_invite_created_b2e6ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["created_at", "is_deleted"],
                name="core_member_created_022165_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["created_at", "is_deleted"],
                name="core_organi_created_40885a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceallocation",
            index=models.Index(
                fields=["created_at", "is_deleted"],
                name="core_resour_created_97c5a9_idx",
            ),
        ),
    ]
