# Generated by Django 5.1.3 on 2024-11-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cluster_is_deleted_deployment_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourceallocation",
            name="allocated_at",
        ),
    ]
